#!/usr/bin/env bash


cat 2>/dev/null > $HOME/.vim/coc-settings.json <<-EOF
{
    // GENERAL CONFIG
    "coc.preferences.extensionUpdateCheck": "weekly",
    "session.directory": "~/.vim/sessions",
    "inlayHint.enable": false,

    // COC-DIAGNOSTICS
    "diagnostic.messageTarget": "float",
    "diagnostic.virtualText": false,
    "diagnostic.virtualTextCurrentLineOnly": false,

    // COC-GIT CONFIG
    "git.enableGutters": true,
    "git.showCommitInFloating": false,
    "git.addedSign.hlGroup": "GitGutterAdd",
    "git.changedSign.hlGroup": "GitGutterChange",
    "git.removedSign.hlGroup": "GitGutterDelete",
    "git.topRemovedSign.hlGroup": "GitGutterDelete",
    "git.changeRemovedSign.hlGroup": "GitGutterChangeDelete",

    // COC-JAVA CONFIG
    "java.project.referencedLibraries": ["~/.vim/gson-2.10.jar"]
}
EOF
