#!/usr/bin/env bash


### convert current note to plain html (~/bin/md2html)
######################################################

md2html $currfile > $pandoc/$1.html




### convert current note to html (pandoc + lua filter)
######################################################

# pandoc $currfile -s --to=html5 -o $pandoc/$1.html \
#             --mathjax \
#             --lua-filter=$pandoc/assets/link2html.lua \
#             -H $pandoc/assets/header.html \
#             -B $pandoc/assets/before.html \
#             -A $pandoc/assets/footer.html \
#             -T $prefixtail




### convert all notes to html (pandoc + lua filter)
###################################################

# for note in *.md; do
#     [[ $note == "README.md" ]] && continue
#     name="${note%.*}"
#     pandoc $note -s --to=html5 -o $pandoc/$name.html \
#                 --mathjax \
#                 --lua-filter=$pandoc/assets/link2html.lua \
#                 -H $pandoc/assets/header.html \
#                 -B $pandoc/assets/before.html \
#                 -A $pandoc/assets/footer.html \
#                 -T $prefixtail
# done




### convert current note to pdf (pandoc + latex)
################################################

# pandoc $currfile --to=pdf -o $pandoc/$1.pdf




### convert all notes to pdf (pandoc + latex)
#############################################

# for note in *.md; do
#     [[ $note == "README.md" ]] && continue
#     name="${note%.*}"
#     pandoc $note --to=pdf -o $pandoc/$name.pdf
# done




### convert current note to slides presentation (pandoc + latex beamer)
#######################################################################

# pandoc $currfile --to=beamer -o $pandoc/$1.pdf
